import { db } from "./firebaseAdmin";
import { whatsappCloudService } from "./whatsappCloudService";

export interface ShoppingItem {
  id: string;
  name: string;
  quantity?: string;
  isPurchased: boolean;
  createdAt: number;
}

const shoppingCollection = () => db.collection("shopping_items");

class ShoppingListService {
  public async addItems(itemsQuery: string): Promise<{ success: boolean; addedCount: number; items: string[]; message: string }> {
    const raw = (itemsQuery || "").trim();
    if (!raw) throw new Error("Shopping items provide karna zaroori hai.");

    // Split by comma, 'and', 'aur', '+'
    const itemNames = raw
      .split(/[,+&]|\band\b|\baur\b/gi)
      .map((i) => i.trim())
      .filter((i) => i.length > 0);

    const now = Date.now();
    for (const name of itemNames) {
      const id = Math.random().toString(36).substring(2, 9);
      await shoppingCollection().doc(id).set({
        id,
        name,
        isPurchased: false,
        createdAt: now,
      });
    }

    const message = `Boss, ${itemNames.length} items shopping list me add kar diye gaye hain: ${itemNames.map((i) => `"${i}"`).join(", ")}!`;

    return {
      success: true,
      addedCount: itemNames.length,
      items: itemNames,
      message,
    };
  }

  public async getShoppingList(): Promise<{ success: boolean; pendingItems: ShoppingItem[]; message: string }> {
    const snap = await shoppingCollection().where("isPurchased", "==", false).get();
    const items: ShoppingItem[] = snap.docs.map((d) => d.data() as ShoppingItem);

    if (items.length === 0) {
      return {
        success: true,
        pendingItems: [],
        message: "Boss, aapki shopping list bilkul khali hai.",
      };
    }

    const message = `Boss, shopping list me total ${items.length} items hain: ${items.map((i) => i.name).join(", ")}.`;

    return {
      success: true,
      pendingItems: items,
      message,
    };
  }

  public async sendListOnWhatsApp(targetPhone?: string): Promise<{ success: boolean; message: string }> {
    const res = await this.getShoppingList();
    if (!res.pendingItems.length) {
      return { success: false, message: "Shopping list khali hai, pehle kuch items add karein." };
    }

    const phone = targetPhone || process.env.BOSS_WHATSAPP_NUMBER || "919999999999";
    let text = `🛒 *FRIDAY — SHOPPING & GROCERY LIST*\n📅 Date: ${new Date().toLocaleDateString("en-IN")}\n\n`;

    res.pendingItems.forEach((item, idx) => {
      text += `⬜ ${idx + 1}. ${item.name}\n`;
    });

    text += `\n_Generated by Friday AI Assistant_`;

    try {
      await whatsappCloudService.sendTextMessage(phone, text);
      return {
        success: true,
        message: `Boss, shopping list aapke WhatsApp number par bhej di gayi hai! (${res.pendingItems.length} items).`,
      };
    } catch (err: any) {
      return {
        success: false,
        message: `WhatsApp par shopping list send nahi ho payi: ${err?.message || err}`,
      };
    }
  }

  public async clearList(): Promise<{ success: boolean; message: string }> {
    const snap = await shoppingCollection().get();
    const batch = db.batch();
    snap.docs.forEach((doc) => batch.delete(doc.ref));
    await batch.commit();

    return {
      success: true,
      message: "Boss, shopping list clear kar di gayi hai!",
    };
  }
}

export const shoppingListService = new ShoppingListService();
